### ISSUE TITLE
Unclear contract of DataFactory.literal

### ISSUE THREAD

**Issue by HolgerKnublauch** [rdfjs/representation-task-force#102]
Currently DataFactory.literal at 

https://github.com/rdfjs/representation-task-force/blob/master/interface-spec.md

claims to take a string languageOrDatatype as second argument. However, the description states that this is either a NamedNode or a string. If it's just a string, how would datatype URIs be distinguished from language tags, so I assume the declared type 'string' needs to be generalized in the documentation.

**Comment by RubenVerborgh** [comment]
It currently states that

> If languageOrDatatype is a NamedNode, then it is used for the value of .datatype. Otherwise languageOrDatatype is used for the value of .language.

Any strings are therefore assumed to be languages, so the case you describe doesn't occur.

However, I'd be interested to still include that case, and make the distinction between both with something like `/:/`.

**Comment by elf-pavlik** [comment]
> `Literal .literal(string value, [string languageOrDatatype])` returns a new instance of Literal. If languageOrDatatype is a NamedNode, then it is used for the value of `.datatype`. Otherwise languageOrDatatype is used for the value of `.language`.

Would changing it to:  `Literal .literal(string value, [string|NamedNode languageOrDatatype])` help? The descriptions clarifies that for language one should pass string and for Datatype one should pass NamedNode

> However, I'd be interested to still include that case, and make the distinction between both with something like /:/.

I think currently all interfaces expect IRIs represented by NamedNode, with only one exception where they appear as strings - when passed as value to namedNode factory.

**Comment by HolgerKnublauch** [comment]
Yes, string|NamedNode is the change that I would suggest.

**Comment by elf-pavlik** [comment]
Thanks @HolgerKnublauch :exclamation: 
PR #103 proposes that clarification
