### ISSUE TITLE
Which value should be used for default graph?

### ISSUE THREAD

**Issue by bergos** [rdfjs/representation-task-force#11]

**Comment by RubenVerborgh** [comment]
Important consideration: if we decide `quads.graph === null` for the default graph, then we can no longer assume for arbitrary quads that we can do `quad.graph.iri`. Therefore, it might make sense to have a constant `.defaultGraph` property on some object to use/compare with.

**Comment by wouterbeek** [comment]
This question interacts with whether multiple datasets are supported or not.  If a user creates more than one dataset then that user also has more than one default graph (one per dataset).

**Comment by miguel76** [comment]
I think it makes sense to use a fixed constant graph name to be used in quads that are in fact triples of the default graph.
Two separates RDF datasets are composed by two distinct set of quads so there is no overlapping.
As an example, Apache Jena uses the IRI <urn:x-arq:DefaultGraph> for this purpose.

**Comment by bergos** [comment]
[Here](https://github.com/rdfjs/representation-task-force/pull/23) is the pull request for the DefaultGraph as interface.

**Comment by l00mi** [comment]
Sorry, I again missed to ask on the mailing list. As you guys seem to have a solution we should go for this and then see what is the feedback after the first release.

**Comment by l00mi** [comment]
https://github.com/rdfjs/representation-task-force/commit/f06307652fa1c127cd84d95efb14f06c9a0d356d
