### ISSUE TITLE
UML diagram updates

### ISSUE THREAD

**Issue by elf-pavlik** [rdfjs/representation-task-force#111]
I hope @pieroit can help us again, let's gather here all needed updates so he can do them at once
* [x] `Literal .literal(string value, [string|NamedNode languageOrDatatype])` #103 
* [x] `error(Error error)` #109

**Comment by jacoscaz** [comment]
I'm not the best at UML but happy to help if needed.

**Comment by elf-pavlik** [comment]
Thank you @jacoscaz you can find SVG sources in https://github.com/rdfjs/representation-task-force/tree/master/img

**Comment by pieroit** [comment]
Roger @elf-pavlik! I'll work on it ASAP ;)
@jacoscaz unless you want to do it... let me know

**Comment by jacoscaz** [comment]
@pieroit I'm more than happy to help if you're busy but equally happy to stand aside if you'd rather do it yourself. Just let me know which diagramming software you're using.

**Comment by pieroit** [comment]
@jacoscaz I'm using draw.io, it's a google drive app.
You should be able to edit:
https://drive.google.com/file/d/0B_YEjqF8ij5sNzZ5VDdZRWtyOEk/view?usp=sharing

**Comment by jacoscaz** [comment]
Yes, I'm able to edit and updated the diagram.

I think some clarification is needed on the EventEmitter/Stream classes. The only event defined at the `EventEmitter` level is the `error:Error` one. Even though any instance of `EventEmitter` can technically emit all kinds of events, I think it'd be nice to have a subclass for the kind of objects returned by methods such as `Sink#import()`.

AFAIK, these objects are not instances of `Stream` but still emit the `end` event. The semantics of such an event, however, are (slightly) different from that of the `end` event emitted by `Stream` instances. The latter signals that a data source has been fully consumed. The former signals that some procedure been completed. The first word that comes to my mind for such a thing is `monitor`.

Also, given the widespread use of `EventEmitter` and `Stream`, I would suggest using more specific class names.  Perhaps `OperationMonitor` and `ReadableQuadStream`? I'm sure that there are better ones out there.

I've updated the draw.io document accordingly to better explain what I mean. Happy to go back to the previous revision if you don't like this.

**Comment by pieroit** [comment]
Welcome @jacoscaz and thank you for the update.

Please note that spec discussion (e.g. naming) is done via issues, gitter and hangouts. The UML diagram is just a visualization of what has already been discussed and (mostly) defined. I think it's a good practice to reason directly on the visualization, but it is not the case for this project and you risk doing more work and not being noticed. Try to intercept discussions before they get documented ;)

**Comment by jacoscaz** [comment]
@pieroit you're absolutely right, my bad. Got over-enthusiastic for a minute or two. I've restored the previous revision and updated the document according to #109 and #103 .

**Comment by pieroit** [comment]
@jacoscaz I feel you!

![image](https://cloud.githubusercontent.com/assets/6328377/24622302/cdaf58f2-18a4-11e7-894f-6de7330a658e.png)

Creative guys in technology suffer a little for the rules.
Your proposal is good, open an issue to get feedback from the community ;)

**Comment by pieroit** [comment]
Made pull request with new diagrams. Also deleted `toCanonical()` methods since they are no more in the spec.

**Comment by elf-pavlik** [comment]
addressed by #114
