### ISSUE TITLE
Reference implementation for the Data Model

### ISSUE THREAD

**Issue by bergos** [rdfjs/representation-task-force#115]
The Data Model is quite simple, but adds boilerplate code to each library. A reference implementation would be useful.

I would propose to use [rdf-data-model](https://github.com/rdf-ext/rdf-data-model/). The additional rdf-ext methods are implemented in a different module. I can move the package, if we agree. I also merged the test suite, because it's easier to maintain.

**Comment by pieroit** [comment]
Agree 👌

**Comment by elf-pavlik** [comment]
@RubenVerborgh @dmitrizagidulin @blake-regalia 

What do you think about moving that reference implementation to @rdfjs orga?

We should also resolve #47 ASAP

**Comment by blake-regalia** [comment]
Sounds good to me

**Comment by RubenVerborgh** [comment]
Okay with making this the reference implementation; does not need to be in the orga for me (but no objection).

**Comment by elf-pavlik** [comment]
We have a reference implementation in orga: https://github.com/rdfjs/data-model
