### ISSUE TITLE
add authors and editors

### ISSUE THREAD

**Issue by bergos** [rdfjs/representation-task-force#119]
One final step would be adding authors and editors based on the document histories.

**Comment by bergos** [comment]
I checked the [contributors list](https://github.com/rdfjs/representation-task-force/graphs/contributors). Everyone mentioned here, can you please add a comment with name, url, company, companyURL for the HTML spec?

@RubenVerborgh @pieroit @elf-pavlik @l00mi @jacoscaz @blake-regalia @dmitrizagidulin

**Comment by RubenVerborgh** [comment]
Thanks, @bergos! If possible, I'd like an editor credit.

Ruben Verborgh
https://ruben.verborgh.org/
Ghent University – imec
http://idlab.ugent.be/

**Comment by pieroit** [comment]
Piero Savastano
http://pieroit.org
Freelance Data Scientist

What is the difference between author and editor?
Thanks

**Comment by l00mi** [comment]
Michael Luggen
http://oiu.ch
Bern University of Applied Sciences
http://www.bfh.ch

**Comment by blake-regalia** [comment]
Blake Regalia
[http://blake-regalia.com/](http://blake-regalia.com/)
STKO Lab @ UCSB
[http://stko.geog.ucsb.edu/](http://stko.geog.ucsb.edu/)

**Comment by bergos** [comment]
@pieroit haven't found a W3C definition, but I think [that definition](http://www.differencebetween.info/difference-between-author-and-editor) also works for us.

I made a [commit](https://github.com/rdfjs/representation-task-force/pull/118/commits/b50c1e2c72f1dff35b05980d240eca2204c64fbf) to my PR with all available credits.

@blake-regalia Your personal URL doesn't work. I removed it now. You have another one or plan to activate the current URL?

@elf-pavlik @jacoscaz @dmitrizagidulin I'm waiting for your feedback.

**Comment by pieroit** [comment]
@bergos thanks. Why did you choose to be editors? You guys (@bergos and @RubenVerborgh ) are the ones that most worked on this.

?

**Comment by elf-pavlik** [comment]
elf Pavlik - https://elf-pavlik.hackers4peace.net (currently just .ttl with WebID Profile Document)

thanks!

@pieroit https://www.w3.org/2017/Process-20170301/#general-requirements
> Every Technical Report published as part of the Technical Report development process is edited by one or more editors appointed by a Group Chair. It is the responsibility of these editors to ensure that the decisions of the Group are correctly reflected in subsequent drafts of the technical report. An editor must be a participant, per section 5.2.1 in the Group responsible for the document(s) they are editing. 

As I understand specs tend to have more authors than editors. I think @bergos and @RubenVerborgh could even appear as both... For example [JSON-LD spec](https://json-ld.org/spec/latest/json-ld/) has all the editors repeated among authors.

**Comment by pieroit** [comment]
Thanks @elf-pavlik I got the distinction now ;)
Authors are partecipants while editors are coordinators. Sounds cool to have them as editors in this sense (and if they want also as authors).

**Comment by elf-pavlik** [comment]
how about including @timbl among authors?

**Comment by bergos** [comment]
@timbl you are not my list, because there is no git commit from you, but I remember especially the NamedNode vs. IRI discussion where your input was used in others PRs. So it's up to you.

Anyone who doesn't leave feedback here will get credits anyway in the acknowledgements section #120.

**Comment by l00mi** [comment]
Lets close this for now, 10days seems like a reasonable amount of time to answer. It is not as if this needs to be the final list anyway.

**Comment by timbl** [comment]
Normally, every editor is also an author..
I do not need to be an author
