### ISSUE TITLE
Typescript discussions

### ISSUE THREAD

**Issue by LaurensRietveld** [rdfjs/representation-task-force#129]
Is this repo the place to discuss the rdf-js npm package typings? 
Couldn't find the guy repo for that project, and would like to discuss some typing issues that don't necessarily require an rdfjs spec discussion

**Comment by elf-pavlik** [comment]
It looks like @rubensworks have published https://www.npmjs.com/package/rdf-js
I see no problem with using this issue to discuss typescript typings.

**Comment by rubensworks** [comment]
Sure, I guess this is a good place to have more in-depth discussions on the rdf-js typings.

Btw, [`@types/rdf-js`](https://www.npmjs.com/package/@types/rdf-js) is the canonical package. [`rdf-js`](https://www.npmjs.com/package/rdf-js) was merely claimed as suggested by the DefinitelyTyped maintainers, but serves no additional purpose.

**Comment by LaurensRietveld** [comment]
Aah, got it. So any PRs to rdf-js should go via definitelytyped?

I see that the spec defines a `Term`, with e.g. `Literal` implementing this interface. The typescript interface follows this definition very closely, by defining a `Term` interface, with other types like `Literal` extending `Term`.

We're not getting enough out of typescript when doing this. Ideally, you could use this typescript interface as this:
`if (quad.subject.termType === 'Literal') console.log(quad.subject.datatype)`

That throws a typescript error right now: `Term` has a termType, but no datatype. What you would like typescript to do is derive it's operating on a `Literal`, and not throw an error.

A solution here is that we'd define the typescript `Term` as `export type Term = NamedNode | Literal | Variable | BlankNode | DefaultGraph`.
We could either keep the old Term interface under a different name so other terms can extend that, or simply remove it (and let typescript derive the union, which should match the spec, considering there are no bugs in either the spec or the ts def)

**Comment by elf-pavlik** [comment]
In https://github.com/linkeddata/rdflib.js/pull/179 @Neur0mante proposed Typescript declaration for rdflib.js I think preferably they should include rdf-js types rather than (re) define them.

**Comment by rubensworks** [comment]
> So any PRs to rdf-js should go via definitelytyped?

Yep, the typings are right here: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/rdf-js

> A solution here is that we'd define the typescript Term as export type Term = NamedNode | Literal | Variable | BlankNode | DefaultGraph.

That change sounds good to me! Once the PR is in, I'll test the typings inside my projects to see if it's backwards-compatible, but I assume it will be.

**Comment by LaurensRietveld** [comment]
I've submitted a PR here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/29836
Let's continue the discussion over there

**Comment by rubensworks** [comment]
We'll probably have to add something to the `Stream` interface to make this work.

In any case, I don't think we should add this now already, quoting @bergos:

> Maybe we can define it in a next version, but I'm not so happy about enforcing it now. Adding it optional, just makes the spec more complicated.

**Comment by LaurensRietveld** [comment]
Indeed, to get this to work you'd need to add something like `[Symbol.asyncIterator](): AsyncIterableIterator<any>;` to the stream interface. (if we're extending the readable node stream interface anyway, and the node typings are >= 10, then this iterator is already defined)

**Comment by elf-pavlik** [comment]
Since Source and Sink also get used by parsers and serializes and have other events like `prefix`, maybe `base` I probably wouldn't use async iteration on them. On the other hand Store could maybe overload `match` return value by adding  `[Symbol.asyncIterator](): AsyncIterableIterator<Quad>` to it.

BTW does anyone work on typing for https://github.com/rdfjs/dataset-spec/ ?
