### ISSUE TITLE
does match considers null as 'optional' parameter value?

### ISSUE THREAD

**Issue by elf-pavlik** [rdfjs/representation-task-force#139]
I've just tried using TypeScript definitions from `@types/rdf-js` by @rubensworks and @LaurensRietveld which [include this line](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e9038e51b914f6a0da5cb559956bfaa35db84735/types/rdf-js/index.d.ts#L356)

```ts
match(subject?: Term | RegExp, predicate?: Term | RegExp, object?: Term | RegExp, graph?: Term | RegExp): Stream<Q>
```

VScode gives me a hint that I can use `undefined` but it seams I can't use `null`, I think current wording in the spec doesn't make it clear: http://rdf.js.org/#source-interface

```webidl
Stream match(optional (Term or RegExp) subject, optional (Term or RegExp) predicate, optional (Term or RegExp) object, optional (Term or RegExp) graph);
```

I thought that since we consider removing `RegExp` from that interface, we could also clarify handling of `null`.

**Comment by rubensworks** [comment]
`null` should match with _any_ term AFAIK. This should indeed be clarified in the spec.

In any case, it's weird that VScode doesn't allow you to use `null`.
We pass `null` [quite frequently in comunica](https://github.com/comunica/comunica/blob/04edbe462c8962cbd198a9643664a5718d21b9c2/packages/actor-rdf-resolve-quad-pattern-hypermedia/test/MediatedQuadSource-test.ts#L149-L163), and our TS compiler doesn't complain about it (we use WebStorm).

**Comment by LaurensRietveld** [comment]
The difference in behavior might be explained by the 'strictNullChecks' flag

**Comment by elf-pavlik** [comment]
Thanks @LaurensRietveld :pray: 

I think we should still make it clear that implementations should treat `null` the same way as `undefined`.
