### ISSUE TITLE
make .equals a factory method?

### ISSUE THREAD

**Issue by elf-pavlik** [rdfjs/representation-task-force#143]
Looking together at #104 and #142 I just wanted to double check this possibility before `data-model` spec ships. Currently Term (with sub classes) and Quad have `.equals()` method, which makes using serializable objects not really an option. Personally I wouldn't mind to just have `.equals()` as method on data factory and instead of:

```js
subject.equals(object)
someStatement.equals(otherStatement)
```
do
```js
eq(subject, object)
eq(someStatement, otherStatement)
```
Besides avoiding issues discussed in #142 it would also allow to easily serialize and de-serialize terms and quads, store them in IndexedDB etc.

I don't say that I think we really should make such change, just checking that we really don't want to do it.

**Comment by RubenVerborgh** [comment]
The underlying question here is the necessity of a pure JSON-deserializable interface. I would say that necessity is not there, given that plenty of syntaxes for RDF exist.

If #137 is considered, then conversion is simple anyway.
