### ISSUE TITLE
Prefix map handling

### ISSUE THREAD

**Issue by bergos** [rdfjs/representation-task-force#15]
Beside triples and quads a serialization may contain a prefix map. A class/interface should be defined to handle that data. Also the source, sink, parser, serializer interfaces should support reading and writing that kind of data.
High level libraries may provide simpler interfaces or utils like a vocab builder to handle prefix maps.

**Comment by RubenVerborgh** [comment]
To what extent is a prefix map an ES6 Map?
The difference is probably that we need symmetry (lookup by both IRI and prefix to get one or the other).

**Comment by bergos** [comment]
We could even defined that it's just a plain object and libraries have to take care how to access it. [RDF-Interfaces](http://www.w3.org/TR/rdf-interfaces/#prefix-maps) has a .resolve and .shrink method that also supports CURIEs. That could be useful. I think this is mainly about finding the balance what belongs to the low level API and what to the high level libraries.

**Comment by RubenVerborgh** [comment]
Do we target the January milestone, or a later one? I'd target a later milestone; while prefix handling is important, it seems not as core as elements like IRIs and triples.

**Comment by bergos** [comment]
+1 for later milestone.

We haven't discussed the content of the milestone in detail yet, but I expect source and sink will be part of a later milestone. The prefix map issue is strongly related to source and sink. We should discuss these topics together.

**Comment by westurner** [comment]
A prefix map must be an ordered map (because of overlapping prefixes)?

**Comment by westurner** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map

> A Map object iterates its elements in insertion order

**Comment by ericprud** [comment]
I think the prefix map need only [map[prefix -> IRI]](http://www.w3.org/TR/turtle/#namespaces).
Round-tripping is not guaranteed because both RDF/XML and Turtle permit redefinition of prefixes.
Any RDF writer app will need a policy e.g. "use longest matching namespace", which will require a specific datastructure, e.g. a [trie](http://en.wikipedia.org/wiki/Trie).

**Comment by elf-pavlik** [comment]
Should we consider #49 while working on this issue?

**Comment by bergos** [comment]
Closed based on the resolution in #136
