### ISSUE TITLE
How to handle data structures which are on top of the graphs ones (s,p,o) like lists and such.

### ISSUE THREAD

**Issue by l00mi** [rdfjs/representation-task-force#16]
In the [meeting](https://github.com/rdfjs/representation-task-force/wiki/Meeting-2015-12-04) we missed consensus on which layer such things should be handled / or how many layers the spec should consider.

**Comment by RubenVerborgh** [comment]
I think the idea was to postpone this for the next milestone.

**Comment by l00mi** [comment]
The discussion of this kind of issues has now started with the next phase of the specification of a common HighLevel API.
