### ISSUE TITLE
How to extend/extra properties of objects

### ISSUE THREAD

**Issue by bergos** [rdfjs/representation-task-force#2]
- Add clause when to use or not to use additional properties
  - Which properties do we include in the spec (source (.why), line, DOM element, ...)?
  - Do we have to care about them? Plain Object factory?

**Comment by RubenVerborgh** [comment]
I think that just one sentence with "object MAY have additional, implementation-specific properties" is sufficient.

**Comment by bergos** [comment]
I created a wiki page for [additional properties](https://github.com/rdfjs/representation-task-force/wiki/Additional-properties) that should be maintained by the community.

**Comment by bergos** [comment]
[Here](https://github.com/rdfjs/representation-task-force/pull/25) is the PR.

**Comment by l00mi** [comment]
29.01.2016 Meeting resolve through PR
