### ISSUE TITLE
Editorial work and adding some examples

### ISSUE THREAD

**Issue by l00mi** [rdfjs/representation-task-force#22]
The spec is a bit dry in the current status.

**Comment by RubenVerborgh** [comment]
@l00mi Was this intended for the _Data mode_ milestone, or is this for later?

**Comment by pieroit** [comment]
Don't know about the milestone but the possible things colud be:
- a UML diagram to easily visualize the architecture
- a set of examples (i.e. creating two triples and comparing them)
I can contribute on both

**Comment by RubenVerborgh** [comment]
That would be great, @pieroit!

However, this makes me think that it should definitely be for a next milestone, in which the document will have a different format as well.

**Comment by pieroit** [comment]
Added a PR with a UML diagram
https://github.com/rdfjs/representation-task-force/pull/27

**Comment by l00mi** [comment]
A UML diagram is great thanks.

@RubenVerborgh: I think we don't need examples and everything for the intermediate milestones. As soon we have implementations using the spec it might be even better just to point to them.
