### ISSUE TITLE
Use streams for source and sink

### ISSUE THREAD

**Issue by bergos** [rdfjs/representation-task-force#39]
Streams are more flexible (pipes, additional events) than per triple callbacks. Therefore the source and sink interfaces should be based on the readable and writable stream interface. There are different standards, but [Node.js streams](https://github.com/nodejs/readable-stream/blob/master/doc/stream.markdown) is the most popular. [WHATWG streams](https://streams.spec.whatwg.org/) could be also interesting because browser will implement them in the future, but at the moment the standard is used very rarely and it's not even ready yet.

**Comment by pieroit** [comment]
Thanks the first link is really useful

**Comment by RubenVerborgh** [comment]
[My proposal for a subset fo Node.js streams](https://github.com/rdfjs/representation-task-force/wiki/Simple-streams).
