### ISSUE TITLE
DefaultGraph extends Term section typo

### ISSUE THREAD

**Issue by dmitrizagidulin** [rdfjs/representation-task-force#42]
In the [DefaultGraph extends Term](https://github.com/rdfjs/representation-task-force/blob/master/interface-spec.md#defaultgraph-extends-term) section, should the following sentence:

`It's only allowed to assign a DefaultGraph to the .graph property of a Quad.`

instead read 

`DefaultGraph is only allowed to be assigned to the .graph property of a Triple.`?

(that is, does the spec mean Triple, instead of Quad?)

**Comment by elf-pavlik** [comment]
@dmitrizagidulin would you like to close this issue?
based on https://gitter.im/linkeddata/rdflib.js?at=56e73531618c335373ebd0a3

**Comment by dmitrizagidulin** [comment]
Addressed in a recent commit. Closing.
