### ISSUE TITLE
Interfaces for source, sink and store

### ISSUE THREAD

**Issue by bergos** [rdfjs/representation-task-force#43]
Here is a proposal for the source, sink and store interface. Feedback is welcome!

### stream.Readable .read([Term|RegExp subject], [Term|RegExp predicate], [Term|RegExp object], [Term|RegExp graph])

The readable stream emits Quad objects. Optional the triple pattern can be used for filtering. Depending on the implementation, filtering could reduce resources and speed up the streaming.

### stream.Writable .write([boolean replace])

Quads object can be written to the stream. If replace is true, existing named graphs will be truncated.

### stream.Writable .delete([Term|RegExp subject], [Term|RegExp predicate], [Term|RegExp object], [Term|RegExp graph])

This method operates in two different modes:

1. Using the triple pattern
The quads matching the triple pattern will be deleted.

2. Without triple pattern
The quads written to the writable stream will be deleted.

### stream.Writable .deleteGraph(IRI|String graph)

Deletes the given named graph. The stream is only used for event handling.

**Comment by bergos** [comment]
We have now a PR for this.

**Comment by westurner** [comment]
stream.Writable.write(``boolean overwrite``) might be less ambiguous than ``boolean replace``? ... semantics

**Comment by dlongley** [comment]
> stream.Writable.write(boolean overwrite) might be less ambiguous than boolean replace? ... semantics

Also, please don't use booleans like this, use an `options` object with the name of the parameter as a key, eg:

```js
stream.write({replace: true});
```

**Comment by bergos** [comment]
I removed that in the PR. I proposed already to have an [optional options parameter](https://github.com/rdfjs/representation-task-force/issues/44). This options object should be used for this case.
