### ISSUE TITLE
Create an interface to shrink and expand CURIEs

### ISSUE THREAD

**Issue by bergos** [rdfjs/representation-task-force#49]
There should be a simple interface to shrink and expand CURIEs. This should be possible for a complete prefix map and also for a single namespace (vocab builder).

**Comment by elf-pavlik** [comment]
https://www.w3.org/TR/rdf-interfaces/#term-maps

seems to support default vocabulary via *setDefault* (sounding similar to JSON-LD `@vocab`) as well as aliases via *set* (reminding me of aliases in JSON-LD `@context`

maybe worth supporting RDF Interfaces Profiles?
https://www.w3.org/TR/rdf-interfaces/#profiles

for example 
>  Because Activity Streams 2.0 can be considered a restricted profile of JSON-LD, Implementations SHOULD consider the `application/ld+json; profile="http://www.w3.org/ns/activitystreams"` media type as being equivalent to `application/activity+json`.

https://www.w3.org/TR/activitystreams-core/#media-type

where http://www.w3.org/ns/activitystreams resolves with JSON-LD `@context`

**Comment by bergos** [comment]
Closed based on the resolution in #136
