### ISSUE TITLE
.value should not have prefixes for variables and blank nodes

### ISSUE THREAD

**Issue by bergos** [rdfjs/representation-task-force#5]

**Comment by RubenVerborgh** [comment]
Agreed during the call.

**Comment by RubenVerborgh** [comment]
See #19.

**Comment by dlongley** [comment]
Not sure where this discussion should be taking place... here's a link to my recent comments:

https://github.com/rdfjs/representation-task-force/pull/19#issuecomment-176852702

**Comment by RubenVerborgh** [comment]
Resolved with #36.
