### ISSUE TITLE
inferred vs. asserted (triples and quads)

### ISSUE THREAD

**Issue by elf-pavlik** [rdfjs/representation-task-force#52]
I would find it helpful to have a common way to distinguish inferred triples from asserted ones. Also asserted triples could provide origin of the assertion in a similar way that rdflib.js uses .why property. .graph doesn't seem to suit this purpose, as we see [in Trig examples of Turtles all the way down article](http://ruben.verborgh.org/blog/2015/10/06/turtles-all-the-way-down/) value of graph can differ (by # fragment) from URL of resource where the assertion come from. [RDF Datasets also don't require graph name to denote the graph](https://www.w3.org/TR/2014/REC-rdf11-concepts-20140225/#section-dataset)

Also during saving the graph, one may prefer not to include inferred triples!

**Comment by RubenVerborgh** [comment]
Makes sense, but is this a feature we should handle on spec level, or is this something individual frameworks can decide upon?

**Comment by elf-pavlik** [comment]
We could at minimum add it to https://github.com/rdfjs/representation-task-force/wiki/Additional-properties and see if we could at some point come up with a common extension.

**Comment by gkellogg** [comment]
Reasoning systems often refer to [A-Box and T-Box](https://en.wikipedia.org/wiki/Tbox) associations. Notionally, the A-Box contains all asserted triples, and the T-Box those that can be logically inferred. Some RDF systems may implement a T-Box using a separate named graph, although this may be confusing for other parts of the pipeline that are sensitive to named-graph semantics.

RDF.rb adds an `#inferred?` method to `RDF::Statement`, which is currently unused, but could be used by reasoners (such as RDFS and RDFa vocabulary expansion) to identify those statements which were added through inference.

**Comment by elf-pavlik** [comment]
It seems as kind of place holder method at this point https://github.com/ruby-rdf/rdf/blob/c33352ace8df20c2097d1da74d1ef260655dba0c/lib/rdf/model/statement.rb#L171-L175

Let's take a use case
* I retrieved certain number of linked data documents which represent social (socioeconomic) data of particular person - Alice <https://alice.example/#identity>  
* All those documents have [Linked Data Signature](https://web-payments.org/specs/source/ld-signatures/) created with a key owned by Alice
* Since I will not write to Alice's dataset, I don't care that much about layout of the API which I used to access the data
* Todo do various reasoning for trust and reputation metrics over my social (socio-economic) graph I create named graphs where I use IRI denoting the verified author of signed statements to name those graphs. This way I collect all statements authored by particular person no matter where this person published them and which API I used to access them.
* I also run reasoner over those named graphs to incorporate mappings between vocabularies like [GoodRelations](http://www.heppnetz.de/projects/goodrelations/) and [ValueFlows](https://valueflo.ws/)
* I would like to keep my resulting dataset still organized with graph names denoting authors of verified statements
* I would like to have straight forward way to distinguish triples which my reasoner inferred from those which Alice asserted in signed documents she published
* optionally I would like to know for each asserted triple, a IRI of signed document which I requested and from which this statement came from

I don't expect from anyone to provide the solution for the use case above, I just thought that it can make it easier to see various assumptions and requirements.

ping @bendiken

**Comment by elf-pavlik** [comment]
We should somehow use wiki page for extended property
