### ISSUE TITLE
define .toCanonical() for instances of DefaultGraph

### ISSUE THREAD

**Issue by elf-pavlik** [rdfjs/representation-task-force#54]
maybe following suggestion in https://github.com/rdfjs/representation-task-force/issues/11#issuecomment-165788703

` urn:x-arq:DefaultGraph`

**Comment by bergos** [comment]
I would propose an empty string as the canonical representation of DefaultGraph.

- no conflict with other Terms (others are wrapped/prefixed with: `<>`, `""`, `_:`, `?`)
- could be used to generate valid N-Triples/N-Quads without condition: `[s,p,o,g].join(' ')+'.'`

**Comment by RubenVerborgh** [comment]
@bergos I disagree with usage of the second argument: internal representations should be independent of serializations.

**Comment by bergos** [comment]
I agree that it should be independent of serializations, but the Quad has also a `.toCanonical()` method and we refer there to the N-Triples spec. So see valid N-Triples/N-Quads as the following arguments:

- allows fast implementations of `.toCanonical()` for the Quad interface
- avoids confusion reading the `.toCanonical()` part of the spec for the Quad interface

**Comment by RubenVerborgh** [comment]
>  Quad has also a .toCanonical() method and we refer there to the N-Triples spec

We should probably avoid that there.
