### ISSUE TITLE
.value of IRI (NamedNode) MUST be a valid IRI?

### ISSUE THREAD

**Issue by elf-pavlik** [rdfjs/representation-task-force#57]
rdf-ext allows creating NamedNode instances which have .nominalValue a **non IRI** string. @bergos [mentioned that some use cases require it](https://gitter.im/rdf-ext/discussions?at=56f164fde247956f1e30047c).

If this spec will allow non IRI .value for an IRI, it should clearly mention it and reference more detailed motivation for such choice.

**Comment by retog** [comment]
The question is if rdfjs should be about RDF or be a bit broader supporting for example the data model of the LDP model where the payload of POST requests is a Turtle with an undefined base URI.

**Comment by elf-pavlik** [comment]
@gkellogg does RDF.rb also allow to create IRI with .value other than valid IRI? If not, how one handles cases like creating new ldp:Resource with HTTP POST?

* https://www.w3.org/TR/ldp-primer/#creating-an-rdf-resource-post-an-rdf-resource-to-an-ldp-bc
* https://gitter.im/linkeddata/rdflib.js?at=56f54e95d39de41b495dba6b

**Comment by gkellogg** [comment]
Creation and validation are different things. Real RDF data has bad terms; you should be able to parse it into a graph and validate either while parsing or once in the graph (or when serializing). A URI is created with a string, it doesn't need to be internally parsed unless validating or performing operations like join.

**Comment by elf-pavlik** [comment]
https://gitter.im/linkeddata/rdflib.js?at=56f7172f8d2a72471b7a79c4

> timbl
17:11
"What if you don't know the URI of the new resource yet? i.e. posting to an LDP container to create a new resource” — good question. My apps always control the URIs of everything completely.
Pragmatic solution:
Invent a hypothetical URI.
like https://foo.databox.me/stuff/app5/newthing/hypothetical.ttl
Then use that as the URI of your doc unment.
Then whenn you serialize the data, you of course use that UIRI as a base. It never appears in the data stream, because of relative URLs.
Then you have to either adjust the graph in the store, or delete it and load the actual file.

**Comment by bergos** [comment]
A validation factory could wrap another factory to throw errors. But it should not be part of the spec.
