### ISSUE TITLE
Specification of .toString should be delegated to implementers

### ISSUE THREAD

**Issue by bergos** [rdfjs/representation-task-force#6]
It is not this library's task to specify the behavior of `.toString`, as specific implementations might like to add different behavior.

**Comment by RubenVerborgh** [comment]
See #7 for a related method that we will specify.

**Comment by RubenVerborgh** [comment]
We should mention that we don't specify `.toString`, and list the related functionality we do have (`.value`, `toCanonical()`).

**Comment by RubenVerborgh** [comment]
See #19.
