### ISSUE TITLE
Rename Literal's `.datatype` to camel cased `.dataType`

### ISSUE THREAD

**Issue by dmitrizagidulin** [rdfjs/representation-task-force#62]
From the call this morning - proposal to rename Literal's `.datatype` property to a camel cased `.dataType` (to match `.termType` and JS convention in general).

**Comment by RubenVerborgh** [comment]
That's a hard one. I follow the comparison with `.termType`, but "datatype" (and in particular `rdf:datatype`)  is one word in most specs.

**Comment by dmitrizagidulin** [comment]
Agreed, and Michael (?) mentioned that point on the call also. The idea here is that Javascript convention overrides the one-word no-lowercase typography of the specs.

**Comment by niklasl** [comment]
RDF datatype is called "datatype" as one word, not two, in all specs and most examples. Calling it `dataType` implies that the notion is called "data type".

It is also named `datatype` in most if not all RDF API:s (i.e. neither `dataType` nor `data_type` depending on the convention of the language). Examples:

* https://jena.apache.org/documentation/javadoc/jena/
* http://rdf4j.org/sesame/2.7/apidocs/org/openrdf/model/Literal.html
* http://librdf.org/docs/pod/RDF/Redland/Node.html
* http://rdflib.readthedocs.org/en/stable/rdf_terms.html#literals
* http://www.rubydoc.info/github/ruby-rdf/rdf/master/RDF/Literal

So I vote for keeping `datatype`.

**Comment by l00mi** [comment]
Its difficult to balance the JS-Universe with the RDF-Universe and still have a consistent naming in this spec. Probably go for datatype and see that we eliminated the camel case in "termType" (https://github.com/rdfjs/representation-task-force/pull/63) by using a shorter name?

**Comment by dlongley** [comment]
@l00mi,

I don't see an inconsistency. "datatype" is one word, so there's nothing to camel case. "Term type" is two words, so you camel case it.

**Comment by dmitrizagidulin** [comment]
@niklasl and @dlongley have a good point, re one word vs two. Changing my mind about this PR, propose we close it.

**Comment by dmitrizagidulin** [comment]
noop - closing.
