### ISSUE TITLE
Name for the spec/standard

### ISSUE THREAD

**Issue by bergos** [rdfjs/representation-task-force#74]
How should we call the sepc/standard? Naming packages like "Parser yx that implements the RDFJS Representation Task Force Interfaces" doesn't look very well. RDFJS Interfaces? There could be a confusion with RDF Interfaces.

**Comment by RubenVerborgh** [comment]
Just RDFJS?

**Comment by dmitrizagidulin** [comment]
+1 to just going with 'RDFJS'

**Comment by RubenVerborgh** [comment]
Or perhaps RDF.js or RDF/JS (to better indicate the two parts).

**Comment by dmitrizagidulin** [comment]
Of those three options, I'd vote for 'RDF/JS'.

**Comment by elf-pavlik** [comment]
* RDF/JS Low Level API
* RDF/JS High Level API

?

**Comment by elf-pavlik** [comment]
closing in favor of #138
