### ISSUE TITLE
Suggest changing `String` to `string`

### ISSUE THREAD

**Issue by blake-regalia** [rdfjs/representation-task-force#76]
`String` typically refers to the String object in javascript, whereas `string` refers to the primitive. For example:
```js
typeof new String('hello');  // 'object'
'hello' instanceof String;  // false
typeof 'hello'; // 'string'
```

The docs seem to indicate that we *acknowledge* the proper casing for `boolean`, e.g., they do not say `Boolean`, which would likewise construct an object. 

As it stands I think it is inconsistent, confusing, and both.

**Comment by bergos** [comment]
@blake-regalia Can you make a PR?

**Comment by blake-regalia** [comment]
2dbd6a36aa69ef1b659bbb34132d6c9185b6159d
