### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by bergos** [rdfjs/representation-task-force#8]
Target is a first complete Draft on mid January 2016

**Comment by RubenVerborgh** [comment]
Created [this milestone](https://github.com/rdfjs/representation-task-force/milestones/First%20complete%20draft) for that. Maybe we can track it there and close this issue?

**Comment by RubenVerborgh** [comment]
Closed with milestones: https://github.com/rdfjs/representation-task-force/milestones?with_issues=no
