### ISSUE TITLE
 low-level API should require that datatypes as Term object and string for language

### ISSUE THREAD

**Issue by bergos** [rdfjs/representation-task-force#83]
This is a comment from @blake-regalia on this [PR](https://github.com/rdfjs/representation-task-force/pull/61#issuecomment-231149938).

> Instead of requiring implementers to test the `languageOrDatatype` string parameter with regex or substring matching; the low-level API should require that datatypes are passed as a Term object, and `string` is reserved for language tags. As pointed out in the conference call, even in "bad practice", RDF formats do allow (and in practice, some users in fact do) use IRIs that don't contain colon characters.

> If an implementer wants to make their API flexible at the cost of extra testing/sanitizing, and allow datatypes to passed as a string, that is their prerogative. The low-level spec should enforce strict typing for the intended use of an argument (i.e., `string` implies language-tag, `object` Term implies datatype)

**Comment by RubenVerborgh** [comment]
:+1:

**Comment by dmitrizagidulin** [comment]
Completely agree with this.

**Comment by elf-pavlik** [comment]
Looks like merging #92 should resolve this issue as well

**Comment by elf-pavlik** [comment]
resolved in #92
