### ISSUE TITLE
Where and how will we work on the HighLevel API?

### ISSUE THREAD

**Issue by l00mi** [rdfjs/representation-task-force#85]
Consensus in 1th Sep Meeting:
- Definition and Issues are in the same Github project as LowLevel API (with labels/tags for Issues)
- Readme explains why two specs and the differences
- Different files for spec
- New proposals will be added as issues with the labels: [proposal](https://github.com/rdfjs/representation-task-force/issues?q=is%3Aopen+is%3Aissue+label%3Aproposal) and [HighLevel API](https://github.com/rdfjs/representation-task-force/labels/HighLevel%20API)

**Comment by elf-pavlik** [comment]
why issues in HiglLevel API milestone have LowLevel API label?
https://github.com/rdfjs/representation-task-force/milestone/4

**Comment by bergos** [comment]
Closed based on the resolution in #136
