### ISSUE TITLE
To reflect the new HighLevel API effort update the Readme to include

### ISSUE THREAD

**Issue by l00mi** [rdfjs/representation-task-force#86]
- How to create new proposals:
  - as issues with the labels: [proposal](https://github.com/rdfjs/representation-task-force/issues?q=is%3Aopen+is%3Aissue+label%3Aproposal) and [HighLevel API](https://github.com/rdfjs/representation-task-force/labels/HighLevel%20API)
  - with the encouragement of adding and usecase
  - two positives statements from core members required to move forward.

**Comment by bergos** [comment]
Closed based on the resolution in #136
