### ISSUE TITLE
Write a Mission Statement for the HighLevel API (analog to LowLevel)

### ISSUE THREAD

**Issue by l00mi** [rdfjs/representation-task-force#87]
In general the two specs should differ like follows:
- low level api ->spec
  - the bare minimum required to interop with other libraries
- common high level api -> spec
  - convenience methods and common operations (building on the low level api primitives)
  - used by more than one library or framework (or _should_ be used by more than one library?)
- high level api frameworks -> not coverd by spec but in separate libraries
  - different view on data, different structure of the api, new querying languages
  - see for example: simplerdf, clownface

**Comment by elf-pavlik** [comment]
should we add @dan-f and https://github.com/dan-f/modelld to examples of frameworks ?

**Comment by RubenVerborgh** [comment]
In a really simple world, for me "RDF/JS Core Interfaces" would be “the minimum building blocks we need for RDF parsers and serializers to talk to each other about the important things” where “important things” is up for discussion.

**Comment by dan-f** [comment]
"the bare minimum required to interop with other libraries" - I'm not finding this informative.

**Comment by RubenVerborgh** [comment]
@dan-f It means there only needs to be one way to do things. Take lists. Low-level shouldn't have an interface for them, because there are already triples.

**Comment by bergos** [comment]
Closed based on the resolution in #136
