### ISSUE TITLE
Define equals using canonical representation

### ISSUE THREAD

**Issue by RubenVerborgh** [rdfjs/representation-task-force#88]
At the moment, equality is defined as:

> `boolean .equals(Term other)` returns `true` if and only if the argument is a) of the same type b) has the same contents (value and, if applicable, type or language)

I propose to rewrite this as

> `boolean .equals(Term other)` returns `true` if and only if the argument has the same canonical representation

for the following reasons:
- “of the same type” is not correct (it implies `instanceof` comparisons), and should be “has the same term type”
- both (the corrected) a) and b) are consequences of the canonical representation
- there is no way to exhaustively test for “same contents”

**Comment by elf-pavlik** [comment]
Should spec include some note about what equality means for blank nodes? Thinking about Gregg's comment in https://github.com/rdfjs/representation-task-force/issues/50#issuecomment-201698108

> for BlankNode being the manifest label doesn't hold up, as if two graphs are merged, blank nodes with the same label aren't merged, as they are different nodes, even if they are labeled the same in a concrete serialization used to instantiate the graph. A graph holds an abstract representation created by parsing a concrete representation into terms; blank node labels are just convenient for a concrete serialization, even if some vestige remains as a graph term.

I can't recall if two different blank nodes in the same dataset can share the same identifier/label

**Comment by RubenVerborgh** [comment]
> Should spec include some note about what equality means for blank nodes?

Yes. It's up to the parser to generate new blank node labels when parsing two different documents that use the same label.

> I can't recall if two different blank nodes in the same dataset can share the same identifier/label

They cannot share in any of the standard RDF syntaxes to serialize a dataset.

**Comment by bergos** [comment]
We had this already [in this PR](https://github.com/rdfjs/representation-task-force/pull/53). We can change it to use `termType` instead of type, so nobody implements it with `instanceof`. But we should keep the rest like it is.

A factory should create unique blank node labels, if the identifier is not given. This should be the default behavior. Reusing the identifier should be an option that must be explicitly enabled.

**Comment by RubenVerborgh** [comment]
> We can change it to use termType instead of type, so nobody implements it with instanceof.

+1

> We had this already in this PR.

Note that my argument was there: `given that .toCanonical might need to perform a computation`; however, if #89 is resolved, that argument might become invalid (all the more if `toCanonical` becomes a property).

So, I think this issue then depends on the solution for #89.

**Comment by RubenVerborgh** [comment]
If we close this issue (as we did with #53), maybe we can simplify the spec by not having `toCanonical` at all. I'm proposing this in #90.

**Comment by elf-pavlik** [comment]
from https://gitter.im/rdfjs/Representation-Task-Force?at=57efd6060ff4ef7a50f76845
> @elf-pavlik 10:28
@bergos @RubenVerborgh should equals() ignore possible additional properties? https://github.com/rdfjs/representation-task-force/wiki/Additional-properties
>  @RubenVerborgh 10:38
@elf-pavlik Yes; I think we should define equals explicitly for each type, and list exhaustively which fields should be compared.
I.e., value for everything except literal, which has value, datatype, language. (And perhaps an exception for blanks.)

I think we should create new issue for above (or PR right away) before closing this one...

**Comment by RubenVerborgh** [comment]
I can PR tomorrow!

**Comment by RubenVerborgh** [comment]
Closing this issue, as the preferred resolution seems to be #90. In addition, I created #91 for a more precise `.equals` behavior.
