### ISSUE TITLE
Can we use ES6 features?

### ISSUE THREAD

**Issue by bergos** [rdfjs/representation-task-force#9]
[ES6 Overview in 350 Bullet Points](https://github.com/bevacqua/es6)

**Comment by l00mi** [comment]
https://babeljs.io/ to be considered if going for ES6 specification.

**Comment by RubenVerborgh** [comment]
I would actually not be against ES6, precisely because transpilers exist.

**Comment by l00mi** [comment]
Well said, ever considered a career as politician? (,

**Comment by nicola** [comment]
+1 for es6

**Comment by bergos** [comment]
also +1, but it should be possible to use a library just with ES5 code. I don't want to force users to use transpilers.

**Comment by RubenVerborgh** [comment]
@bergos Could you clarify "it should be possible to use a library just with ES5 code"?

**Comment by bergos** [comment]
It should be possible to just transpile a library and use the output with ES5 code. We should define alternatives in the interfaces if we use stuff like import, generators or other features which can't be implemented with polyfills. I want to make sure you can do stuff like:

```
<script src="rdf-lib-transpiled.js"></script>
<script>
  var literal = rdf.literal('thisIsES5Code')
<script>
```

Sure, we define a low level API, but beside the developers ES6 know-how there could be other limitations/restrictions. E.g. company guide lines.

**Comment by RubenVerborgh** [comment]
Alright, we might have to see what the limits are of using a transpiled ES6 library in ES5 (as opposed to programming an application in ES6 and then transpiling).

**Comment by bergos** [comment]
Don't required at the moment. Reopen if we would benifit from ES6 features.
