### ISSUE TITLE
Add .toJSON on Term and Quad

### ISSUE THREAD

**Issue by RubenVerborgh** [rdfjs/representation-task-force#94]
I propose to add a `.toJSON` method on Term and Quad, which returns a JSON object with all mandatory properties, from which the original can be reconstructed.

For example, the result of `myNamedNode.toJSON()` could be:

```
{
    "termType": "NamedNode",
    "value": "http://example.org/"
}
```

It might be confusing that this is an object rather than stringified JSON; perhaps a more appropriate name is `toObject`.

**Vote:** :+1: to have this in low-level API, 😄  to have this in high-level API, :-1: to not have it in either

**Comment by RubenVerborgh** [comment]
Here is an example implementation: https://github.com/RubenVerborgh/N3.js/commit/ccbbad49a23e557a82b27c6cae876241f92c4211

Note that this implementation can actually be reused for all implementations; however, some might have faster ways to create the result.

**Comment by bergos** [comment]
I think we should move it to the high level API, because it's more a util method, which can be implemented on top of the low level API.

**Comment by RubenVerborgh** [comment]
> it's more a util method

True!

> I think we should move it to the high level API

Can/does the high-level API extend objects from the low-level API like `Term`?

**Comment by bergos** [comment]
> Can/does the high-level API extend objects from the low-level API such as Term?

Yes, we have the factory therefore. It's also a requirement for the `.toCanonical` / `.toNT` method.

**Comment by RubenVerborgh** [comment]
Okay! I have added voting options above.

**Comment by blake-regalia** [comment]
I feel like there needs to be some standard way of serializing Terms from the low-level API, whether it's for debugging, exporting, or interchange between libraries. This seems like a simple and direct way to do that.

> it's more a util method

I think that any other serialization formats definitely belong in the high-level API (e.g., `.toNT`), because those really aren't directly related to Javascript. However, JSON is the defacto data format for js, and it's a trivial few lines of code to implement.

**Comment by elf-pavlik** [comment]
Resolution from a call: *unless there is a clear use case (then we can re-discuss), move this issue to the High Level API (instead of Low Level)*

**Comment by blake-regalia** [comment]
After some discussion, I realize that peer libraries can simply use interface methods to obtain data from Terms and Quads; so at this time, it seems that a `.toObject()` method really does not have a strong use-case for the low-level API.

**Comment by iddan** [comment]
What would be a use case for this method?

**Comment by RubenVerborgh** [comment]
I don’t see any actually; happy to close.
