### ISSUE TITLE
Stream events for parsing various serialization formats

### ISSUE THREAD

**Issue by blake-regalia** [rdfjs/representation-task-force#97]
Having a `prefix` event in the specification is an auxiliary feature, i.e., it is not part of the core functionality, because it only applies to certain serialization formats. The same goes for other events such as: `base`, `graph_open`, `graph_close`, and so on.

Clearly, these are useful events to have in an implementation - but _requiring_ them in an interface is somewhat ambiguous since they are not universal. It would also mean that the interface would have to specify which events are required by which serialization formats, a list that will keep on growing.

I suggest removing `prefix` from the low level API and simply allow implementers to decide if certain auxiliary events are suitable for their parsers. Since it is keen to have standard names for events for interoperability, perhaps we could provide a list of names for those events.

**Comment by elf-pavlik** [comment]
If on `data` we can read quads from the parser, they already include the graph name. I don't understand why the parser needs to expose graph_open and graph_close?

As for prefix, base etc. maybe a single event `meta` or `context` would work and consumers could expect to handle prefix, base, maybe even term maps which JSON-LD context can include.

**Comment by blake-regalia** [comment]
@elf-pavlik : For graphy.js, I emit `graph_open` and `graph_close` events for a specific use-case, which it has a tremendous performance benefits on: [as I show in this example](https://github.com/blake-regalia/graphy.js#parse_triginput-stream-config-hash).

My point in this issue is that these events are auxiliary and that they **don't** deserve their own designation in the specification because they are merely artifacts of some serialization format. If we included these in the spec in any form, we would immediately be dismissing all future and other arbitrary serialization delimiters and grammar state changes. *Requiring them* makes no sense. Therefore, these really do not belong in a low-level interface.

**Comment by RubenVerborgh** [comment]
@blake-regalia Artefacts, yes, but prefixes are rather important artefacts compared to opening and closing graphs. They might be used for autocompletion etc.

**Comment by elf-pavlik** [comment]
Currently we have `prefix` in the draft but don't define how to model them #15 
I lean towards what @blake-regalia proposes here and only have `readable`, `data`, `end`, `error` and for all the 'additional events' create a reference similar to https://github.com/rdfjs/representation-task-force/wiki/Additional-properties

**Comment by blake-regalia** [comment]
@RubenVerborgh I absolutely agree that they are useful events, but consider the consequences of _requiring_ them. The specification would have to include a comprehensive list of which serialization formats the `prefix` event applies to. Conversely, it would also have to indicate that the other formats _should not_ emit prefix events (otherwise there is ambiguity).

And what about new formats or proprietary ones? Do certain JSON-LD contexts count as prefixes? What about the dictionary portion of HDT? Why not include other events that are useful but only apply to a subset of formats? Ultimately, staying up-to-date with new and evolving serialization formats challenges the sustainability of our standard. 

I support what @elf-pavlik suggests. Perhaps we could even standardize the definition of a `prefix`event, but just have it be optional instead of required.

**Comment by RubenVerborgh** [comment]
I'm fine with that! As far a a definition goes, we probably can go for a `prefix` event with a prefix (string) and NamedNode parameter.

**Comment by niklasl** [comment]
I guess `base` should be on par with `prefix`? Preserving relative URIs is a useful feature for various tools. (See e.g. https://www.w3.org/DesignIssues/Relative.)

(I can see how it is a slippery slope though, since considering `language` pops up in my mind too, thinking of its use in e.g. RDF/XML and RDFa (and to a lesser extent in JSON-LD). I don't consider that as common as `base` and `prefix` though.)

**Comment by bergos** [comment]
Closed based on the resolution in #136
